import React, { useState, useRef, useMemo, useEffect } from 'react';
import { useHistory, useParams, useLocation } from "react-router"
import { useDispatch, useSelector, useStore } from 'react-redux'
import {
    Button,
    Card,
    CardHead,
    CardHeadMain,
    CardHeadActions,
    CardBody,
    Nav,
    NavGroup,
    NavItem,
    NavItemSeparator,
    NavList,
    NavVariants,
    Page,
    PageHeader,
    PageSection,
    PageSidebar,
    Title,
    Toolbar,
    ToolbarGroup,
    ToolbarItem,
} from '@patternfly/react-core';
import {
    Area,
    Bar,
    Label,
    Legend,
    ComposedChart,
    Line,
    CartesianGrid,
    XAxis,
    YAxis,
    Tooltip,
    ReferenceArea,
    ReferenceLine,
    ResponsiveContainer,
} from 'recharts';